import { v4 as uuidv4 } from "uuid";
import { parseDanmu } from "../danmu/index.js";
import { detectSignals } from "./signalDetector.js";
import { rankCandidates, preRankCandidates } from "./llmRanker.js";
import { detectSuspicious, applyFilter, llmReviewPatterns } from "./danmakuFilter.js";
import { understandContent } from "./contentUnderstanding.js";
import { generateStyledTitles } from "./titleStyler.js";
import { refineBoundaries } from "./boundaryRefiner.js";
import { getVideoDuration } from "./exportPipeline.js";
import logger from "../utils/log.js";

import { buildEvidence } from "./evidence.js";

import type { AutoClipConfig, DanmakuFilterRule } from "@biliLive-tools/types";
import type {
  AutoClipResult,
  DanmuStats,
  HighlightSegment,
  SuspiciousPattern,
  TitleStyleConfig,
  BoundaryRefinement,
} from "./types.js";

function checkAborted(signal?: AbortSignal): void {
  signal?.throwIfAborted();
}

export type ProgressCallback = (stage: string, pct: number, message: string) => void;

export interface PipelineParams {
  videoPath: string;
  danmuPath: string;
  presetConfig: AutoClipConfig;
  onProgress?: ProgressCallback;
  sendMessage?: (prompt: string, signal?: AbortSignal) => Promise<string>;
  sendMultimodalMessage?: (
    prompt: string,
    images: string[],
    signal?: AbortSignal,
  ) => Promise<string>;
  recognizeASR?: (audioPath: string) => Promise<{ text: string }>;
  ffmpegPath?: string;
  id?: string;
  signal?: AbortSignal;
}

/**
 * Main auto-clip pipeline:
 *   1. Parse danmaku XML → DanmuStats
 *   2. Layer 1: detect signal candidate windows
 *   3. Layer 2: LLM rank (or heuristic pre-rank if LLM disabled)
 *   4. Return AutoClipResult
 */
export async function runAutoClipPipeline(params: PipelineParams): Promise<AutoClipResult> {
  const {
    videoPath,
    danmuPath,
    presetConfig,
    onProgress,
    sendMessage,
    sendMultimodalMessage,
    recognizeASR,
    signal,
  } = params;
  const id = params.id ?? uuidv4();

  const llmFallback = presetConfig.llm.enabled && !sendMessage;

  onProgress?.("parse", 0, "Parsing danmaku...");

  // 1. Parse danmaku
  const parsed = await parseDanmu(danmuPath);

  checkAborted(signal);

  const duration = await getVideoDuration(videoPath);

  const stats: DanmuStats = {
    danmu: parsed.danmu,
    sc: parsed.sc,
    gift: parsed.gift,
    guard: parsed.guard,
    videoStartTime: parsed.metadata.video_start_time ?? 0,
    duration,
  };

  onProgress?.("parse", 20, `Danmaku parsed: ${stats.danmu.length} danmaku, ${stats.sc.length} SC`);

  // 1.5: Danmaku filtering (detect → LLM review → apply)
  let suspiciousPatterns: SuspiciousPattern[] | undefined;
  let danmakuFilterStats: AutoClipResult["danmakuFilterStats"] | undefined;
  const filterConfig = presetConfig.danmakuFilter ?? {
    enabled: true,
    rules: [],
    autoDetectEnabled: true,
  };
  const autoGeneratedRules: DanmakuFilterRule[] = [];
  if (filterConfig.enabled && stats.danmu.length > 0) {
    const totalBefore = stats.danmu.length;

    if (filterConfig.autoDetectEnabled) {
      suspiciousPatterns = detectSuspicious(stats.danmu as Array<{ text: string }>);
      if (suspiciousPatterns.length > 0) {
        onProgress?.(
          "filter",
          25,
          `Detected ${suspiciousPatterns.length} suspicious danmaku patterns`,
        );

        if (sendMessage) {
          const reviewResult = await llmReviewPatterns(suspiciousPatterns, sendMessage, signal);
          suspiciousPatterns = reviewResult.patterns.map((p) => ({
            text: p.text,
            count: suspiciousPatterns!.find((sp) => sp.text === p.text)?.count ?? 0,
            similarity: suspiciousPatterns!.find((sp) => sp.text === p.text)?.similarity ?? 1.0,
            llmVerdict: p.verdict,
            llmReason: p.reason,
          }));

          if (reviewResult.newRules.length > 0) {
            autoGeneratedRules.push(...reviewResult.newRules);
            onProgress?.(
              "filter",
              28,
              `LLM confirmed ${reviewResult.newRules.length} spam patterns`,
            );
          }
        } else {
          onProgress?.(
            "filter",
            25,
            `Suspicious patterns detected (LLM unavailable, using statistical fallback)`,
          );
          const now = Date.now();
          for (const p of suspiciousPatterns) {
            if (p.count >= 10 && p.similarity >= 0.9) {
              autoGeneratedRules.push({
                id: uuidv4(),
                pattern: p.text,
                mode: p.similarity >= 0.95 ? "exact" : "contains",
                source: "auto",
                enabled: true,
                createdAt: now,
              });
            }
          }
        }
      }
    }

    const effectiveRules = [...filterConfig.rules, ...autoGeneratedRules];
    let filterResult:
      | {
          filtered: typeof stats.danmu;
          removed: number;
          breakdown: Array<{ ruleId: string; pattern: string; removed: number }>;
        }
      | undefined;
    if (effectiveRules.length > 0) {
      filterResult = applyFilter(stats.danmu, { ...filterConfig, rules: effectiveRules });
      stats.danmu = filterResult.filtered;
      onProgress?.(
        "filter",
        30,
        `Filtered ${filterResult.removed}/${totalBefore} danmaku (${filterResult.breakdown.length} rules)`,
      );
    }
    if (filterResult) {
      danmakuFilterStats = {
        totalBefore,
        totalAfter: filterResult.filtered.length,
        removed: filterResult.removed,
        breakdown: filterResult.breakdown,
      };
    }
  }

  checkAborted(signal);

  // 2. Layer 1: Signal detection
  const { candidates, densityBuckets } = detectSignals(
    stats,
    presetConfig.signal,
    presetConfig.llm.danmakuSampleMax,
  );

  if (candidates.length === 0) {
    onProgress?.("skip", 100, "No highlight signals detected, skipping");
    return {
      id,
      videoPath,
      danmuPath,
      highlights: [],
      skipped: true,
      skippedReason: "no_signal",
      llmFallback,
      suspiciousPatterns,
      danmakuFilterStats,
      autoGeneratedRules: autoGeneratedRules.length > 0 ? autoGeneratedRules : undefined,
    };
  }

  onProgress?.("detect", 50, `Detected ${candidates.length} candidate windows`);

  // Capture danmaku density curve + trigger danmaku for evidence
  const evidenceDanmakuCurve = densityBuckets;
  const evidenceTriggerDanmaku: Array<{ timeOffset: number; text: string; user?: string }> = [];
  for (const c of candidates) {
    for (const s of c.danmakuSample) {
      evidenceTriggerDanmaku.push({ timeOffset: s.timeOffset, text: s.text, user: s.user });
    }
  }
  // Compute overall signal density stats for evidence
  const maxDensity = densityBuckets.reduce((m, b) => Math.max(m, b.density), 0);
  const evidenceSignalDetails = {
    actualDensity: Math.round(maxDensity * 100) / 100,
    threshold: 0, // filled after LLM ranking
    sources: [...new Set(candidates.flatMap((c) => c.signalSources.map((s) => s)))],
    mergedWindows: candidates.map((c) => ({ start: c.timeRange[0], end: c.timeRange[1] })),
  };

  // 3. Layer 2: LLM ranking (or heuristic fallback)
  let highlights: HighlightSegment[];

  if (presetConfig.llm.enabled && sendMessage) {
    onProgress?.("rank", 60, "LLM ranking in progress...");
    const allDanmaku = stats.danmu.map((d) => ({
      sec: d.timestamp ?? d.ts / 1000,
      text: d.text ?? "",
    }));
    highlights = await rankCandidates(
      candidates,
      presetConfig.llm,
      sendMessage,
      allDanmaku,
      signal,
    );
    onProgress?.("rank", 80, `LLM ranking complete: ${highlights.length} highlights kept`);
  } else {
    // Without LLM, use pre-rank heuristic and wrap as HighlightSegment
    if (llmFallback) {
      logger.warn(
        "AutoClip: LLM enabled but sendMessage unavailable — AI config may be incomplete, falling back to heuristic ranking",
      );
    }
    const ranked = preRankCandidates(candidates, presetConfig.llm.topK);
    highlights = ranked.map((c) => ({
      timeRange: c.timeRange,
      bestRange: c.timeRange,
      score: 5,
      title: "Highlight",
      tags: [],
      highlightType: "hype" as const,
      reason: "Auto-detected (no LLM)",
      signalSources: c.signalSources,
      isHighlight: true,
    }));
  }

  checkAborted(signal);

  // Refinements may be populated during boundary refinement phase; used for evidence later
  let evidenceRefinements: BoundaryRefinement[] = [];

  // Build TitleStyleConfig from presetConfig.llm
  const titleStyleConfig: TitleStyleConfig | undefined =
    presetConfig.llm.titleStyleConfig || presetConfig.llm.titleStylePrompt
      ? {
          maxLength: presetConfig.llm.titleStyleConfig?.maxLength ?? 30,
          minLength: presetConfig.llm.titleStyleConfig?.minLength ?? 20,
          customPrompt: presetConfig.llm.titleStylePrompt || undefined,
        }
      : undefined;

  // 3.5 Phase 1.5: Content understanding + Phase 2: Styled titles
  if (highlights.length > 0 && sendMessage) {
    const enhancement = presetConfig.enhancement;
    const hasEnhancement = enhancement?.asrEnabled || enhancement?.visualEnabled;

    if (hasEnhancement) {
      onProgress?.("understand", 82, "Content understanding (ASR + visual)...");
      try {
        const { asrMap, frameMap } = await understandContent(
          videoPath,
          highlights,
          enhancement,
          { sendMultimodalMessage, recognizeASR, ffmpegPath: params.ffmpegPath },
          signal,
        );
        onProgress?.("understand", 88, "Content understanding complete");

        // Phase 1.6: Boundary refinement
        if (presetConfig.enhancement.boundaryRefineEnabled) {
          onProgress?.("refine", 89, "Refining clip boundaries...");
          try {
            const refineConfig = presetConfig.enhancement?.boundaryRefine ?? {};
            const refined = await refineBoundaries(
              highlights,
              asrMap,
              frameMap,
              sendMessage,
              refineConfig,
              duration,
              signal,
            );
            highlights = refined.highlights;
            evidenceRefinements = refined.refinements;
            onProgress?.("refine", 92, "Boundaries refined");
          } catch (err) {
            logger.warn("AutoClip: boundary refinement failed, using original boundaries", err);
          }
        }

        onProgress?.("title", 90, "Generating styled titles...");
        highlights = await generateStyledTitles(
          highlights,
          { asrMap, frameMap },
          sendMessage,
          titleStyleConfig,
          signal,
        );
        onProgress?.("title", 95, `Styled titles generated for ${highlights.length} clips`);
      } catch (err) {
        logger.warn(
          "AutoClip: content understanding / title styling failed, using Phase 1 titles",
          err,
        );
      }
    } else {
      // Phase 2 only (no Phase 1.5 enrichment)
      onProgress?.("title", 90, "Generating styled titles...");
      try {
        highlights = await generateStyledTitles(
          highlights,
          { asrMap: new Map(), frameMap: new Map() },
          sendMessage,
          titleStyleConfig,
          signal,
        );
        onProgress?.("title", 95, `Styled titles generated for ${highlights.length} clips`);
      } catch (err) {
        logger.warn("AutoClip: title styling failed, using Phase 1 content summaries", err);
      }
    }
  }

  checkAborted(signal);

  onProgress?.("done", 100, `Complete: ${highlights.length} highlights`);

  // Build evidence chain (non-blocking: failure → evidence = undefined)
  let evidence: AutoClipResult["evidence"];
  try {
    evidence = buildEvidence({
      densityBuckets: evidenceDanmakuCurve,
      highlights,
      refinements: evidenceRefinements,
      triggerDanmaku: evidenceTriggerDanmaku,
      signalDetails: evidenceSignalDetails,
    });
  } catch (err) {
    logger.warn("AutoClip: evidence building failed, continuing without evidence", err);
  }

  return {
    id,
    videoPath,
    danmuPath,
    highlights,
    llmFallback,
    suspiciousPatterns,
    danmakuFilterStats,
    autoGeneratedRules: autoGeneratedRules.length > 0 ? autoGeneratedRules : undefined,
    evidence,
  };
}

// Re-export export types and functions (moved to exportPipeline.ts for separation of concerns)
export {
  type DanmakuStatus,
  type ExportClipsResult,
  type ExportPresetContext,
  type ExportClipByIdResult,
  type ExportClipByIdDeps,
  resolveExportPresets,
  exportClips,
  resolveSavePath,
  doExportClips,
  validateAndNormalizeHighlight,
} from "./exportPipeline.js";
